/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.beans.Categoria;
import modelo.beans.Producto;
import modelo.logic.CategoriaLogic;
import modelo.logic.ProductoLogic;

/**
 *
 * @author COMPUTER
 */

public class FrmRegistrarProducto extends javax.swing.JDialog {
private Producto producto;
   
    /**
     * Creates new form FrmRegistrarProducto
     */
    public FrmRegistrarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
             this.setLocationRelativeTo(null);
        cargarComboCategoria();
        cargarTablaProducto();
    }

    
    private void cargarComboCategoria(){
        comboModel = CategoriaLogic.comboModelCategoria();
        cmbcategoria.setModel(comboModel);
    }
    
    private void cargarTablaProducto(){
        tableModel = ProductoLogic.tableModelProducto();
        tblproducto.setModel(tableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproducto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        cmbcategoria = new javax.swing.JComboBox<>();
        btnmodify = new javax.swing.JPanel();
        modifyBtnTxt = new javax.swing.JLabel();
        btndelete = new javax.swing.JPanel();
        deleteBtnTxt = new javax.swing.JLabel();
        btnexit = new javax.swing.JPanel();
        exitBtnTxt = new javax.swing.JLabel();
        btnupload = new javax.swing.JPanel();
        uploadBtnTxt1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblimage = new javax.swing.JLabel();
        btninsert = new javax.swing.JPanel();
        insertBtnTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Producto");

        PanelGeneral.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(122, 204, 202));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(122, 204, 202));

        tblproducto.setAutoCreateRowSorter(true);
        tblproducto.setBackground(new java.awt.Color(102, 102, 102));
        tblproducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproducto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "LLENA LOS CAMPOS PEDIDOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Codigo");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Stock");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Precio");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Categoria");

        txtcodigo.setBackground(new java.awt.Color(51, 51, 51));
        txtcodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtcodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtnombre.setBackground(new java.awt.Color(51, 51, 51));
        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtprecio.setBackground(new java.awt.Color(51, 51, 51));
        txtprecio.setForeground(new java.awt.Color(255, 255, 255));
        txtprecio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtstock.setBackground(new java.awt.Color(51, 51, 51));
        txtstock.setForeground(new java.awt.Color(255, 255, 255));
        txtstock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbcategoria.setBackground(new java.awt.Color(51, 51, 51));
        cmbcategoria.setForeground(new java.awt.Color(255, 255, 255));
        cmbcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cmbcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnmodify.setBackground(new java.awt.Color(122, 204, 202));
        btnmodify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        modifyBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        modifyBtnTxt.setForeground(new java.awt.Color(51, 51, 51));
        modifyBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyBtnTxt.setText("MODIFICAR");
        modifyBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnmodifyLayout = new javax.swing.GroupLayout(btnmodify);
        btnmodify.setLayout(btnmodifyLayout);
        btnmodifyLayout.setHorizontalGroup(
            btnmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modifyBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnmodifyLayout.setVerticalGroup(
            btnmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modifyBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btndelete.setBackground(new java.awt.Color(122, 204, 202));
        btndelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deleteBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        deleteBtnTxt.setForeground(new java.awt.Color(51, 51, 51));
        deleteBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteBtnTxt.setText("ELIMINAR");
        deleteBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btndeleteLayout = new javax.swing.GroupLayout(btndelete);
        btndelete.setLayout(btndeleteLayout);
        btndeleteLayout.setHorizontalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btndeleteLayout.setVerticalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnexit.setBackground(new java.awt.Color(122, 204, 202));
        btnexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        exitBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        exitBtnTxt.setForeground(new java.awt.Color(51, 51, 51));
        exitBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtnTxt.setText("SALIR");
        exitBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnexitLayout = new javax.swing.GroupLayout(btnexit);
        btnexit.setLayout(btnexitLayout);
        btnexitLayout.setHorizontalGroup(
            btnexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnexitLayout.setVerticalGroup(
            btnexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btnupload.setBackground(new java.awt.Color(122, 204, 202));
        btnupload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        uploadBtnTxt1.setBackground(new java.awt.Color(51, 51, 51));
        uploadBtnTxt1.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        uploadBtnTxt1.setForeground(new java.awt.Color(0, 0, 0));
        uploadBtnTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uploadBtnTxt1.setText("SUBIR IMAGEN");
        uploadBtnTxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadBtnTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadBtnTxt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uploadBtnTxt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uploadBtnTxt1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnuploadLayout = new javax.swing.GroupLayout(btnupload);
        btnupload.setLayout(btnuploadLayout);
        btnuploadLayout.setHorizontalGroup(
            btnuploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uploadBtnTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        btnuploadLayout.setVerticalGroup(
            btnuploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uploadBtnTxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setToolTipText("");

        lblimage.setIcon(lblimage.getIcon());
        lblimage.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblimageInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btninsert.setBackground(new java.awt.Color(122, 204, 202));
        btninsert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        insertBtnTxt.setBackground(new java.awt.Color(51, 51, 51));
        insertBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        insertBtnTxt.setForeground(new java.awt.Color(0, 0, 0));
        insertBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insertBtnTxt.setText("INSERTAR");
        insertBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btninsertLayout = new javax.swing.GroupLayout(btninsert);
        btninsert.setLayout(btninsertLayout);
        btninsertLayout.setHorizontalGroup(
            btninsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btninsertLayout.setVerticalGroup(
            btninsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelGeneralLayout.createSequentialGroup()
                                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btninsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnupload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnmodify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGeneralLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btninsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGeneralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmodify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductoMouseClicked
        int seleccionar = tblproducto.rowAtPoint(evt.getPoint());
        txtcodigo.setText(String.valueOf(tblproducto.getValueAt(seleccionar,0)));
        txtnombre.setText(String.valueOf(tblproducto.getValueAt(seleccionar,1)));
        txtprecio.setText(String.valueOf(tblproducto.getValueAt(seleccionar,2)));
        txtstock.setText(String.valueOf(tblproducto.getValueAt(seleccionar,3)));
        cmbcategoria.setActionCommand(String.valueOf(tblproducto.getValueAt(seleccionar, 4)));
        lblimage.setIcon((Icon)tblproducto.getValueAt(seleccionar,5));
    }//GEN-LAST:event_tblproductoMouseClicked

    private void insertBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnTxtMouseClicked
        // TODO add your handling code here:
       try{
            int codigo = Integer.parseInt(txtcodigo.getText());
            String nombre = txtnombre.getText();
            double precio = Double.parseDouble(txtprecio.getText());
            int stock = Integer.parseInt(txtstock.getText());
            Categoria cat = (Categoria) cmbcategoria.getSelectedItem();
            Icon img = lblimage.getIcon();
            
            producto = new Producto(codigo,nombre,precio,stock,cat,img);
            if(ProductoLogic.insertarProducto(producto)){
                JOptionPane.showMessageDialog(this, "Se insertó correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "Error al insertar");
            }
            this.cargarTablaProducto();
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        txtcodigo.setText("");
        txtnombre.setText("");
        txtprecio.setText("");
        txtstock.setText("");
        lblimage.setIcon(null);
    }//GEN-LAST:event_insertBtnTxtMouseClicked

    private void insertBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnTxtMouseEntered
        // TODO add your handling code here:
        btninsert.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_insertBtnTxtMouseEntered

    private void insertBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnTxtMouseExited
        // TODO add your handling code here:
        btninsert.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_insertBtnTxtMouseExited

    private void modifyBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyBtnTxtMouseClicked

        try{
            int codigo = Integer.parseInt(txtcodigo.getText());
            String nombre = txtnombre.getText();
            double precio = Double.parseDouble(txtprecio.getText());
            int stock = Integer.parseInt(txtstock.getText());
            Categoria cat = (Categoria) cmbcategoria.getSelectedItem();
            Icon img = lblimage.getIcon();
            producto = new Producto(codigo,nombre,precio,stock,cat,img);
            
            if(ProductoLogic.modificarProducto(producto)){
                JOptionPane.showMessageDialog(this, "Se modificó correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo modificar");
            }
            this.cargarTablaProducto();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        txtcodigo.setText("");
        txtnombre.setText("");
        txtprecio.setText("");
        txtstock.setText("");
        lblimage.setIcon(null);
    }//GEN-LAST:event_modifyBtnTxtMouseClicked

    private void modifyBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyBtnTxtMouseEntered
        btnmodify.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_modifyBtnTxtMouseEntered

    private void modifyBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyBtnTxtMouseExited
        btnmodify.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_modifyBtnTxtMouseExited

    private void deleteBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnTxtMouseClicked
        // TODO add your handling code here:
        try{
            int codigo = Integer.parseInt(txtcodigo.getText());
            
            if(ProductoLogic.eliminarProducto(codigo)){
                JOptionPane.showMessageDialog(this, "Se eliminó correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar");
            }
            this.cargarTablaProducto();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        txtcodigo.setText("");
        txtnombre.setText("");
        txtprecio.setText("");
        txtstock.setText("");
        lblimage.setIcon(null);
    }//GEN-LAST:event_deleteBtnTxtMouseClicked

    private void deleteBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnTxtMouseEntered
        // TODO add your handling code here:
        btndelete.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_deleteBtnTxtMouseEntered

    private void deleteBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnTxtMouseExited
        // TODO add your handling code here:
        btndelete.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_deleteBtnTxtMouseExited

    private void exitBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnTxtMouseClicked
        // TODO add your handling code here:
        int valor;
        valor = JOptionPane.showConfirmDialog(this,"¿Seguro que desea salir?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION){
            this.dispose();
        
        }
    }//GEN-LAST:event_exitBtnTxtMouseClicked

    private void exitBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnTxtMouseEntered
        // TODO add your handling code here:
        btnexit.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_exitBtnTxtMouseEntered

    private void exitBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnTxtMouseExited
        // TODO add your handling code here:
        btnexit.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_exitBtnTxtMouseExited

    private void cmbcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcategoriaActionPerformed

    private void uploadBtnTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadBtnTxt1MouseClicked
        // TODO add your handling code here:
        String fuente="";
        JFileChooser chooser=new JFileChooser();
        FileNameExtensionFilter format = new FileNameExtensionFilter("JPG,PNG","jpg","png");
        chooser.setFileFilter(format);
    
        int rpta= chooser.showOpenDialog(this);
        if (rpta==JFileChooser.APPROVE_OPTION) {
            fuente=chooser.getSelectedFile().getPath();
            Image img=new ImageIcon(fuente).getImage();
            ImageIcon icono=new ImageIcon(img.getScaledInstance(lblimage.getWidth(), lblimage.getHeight(),Image.SCALE_SMOOTH));
            lblimage.setIcon(icono);
       }
    }//GEN-LAST:event_uploadBtnTxt1MouseClicked

    private void uploadBtnTxt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadBtnTxt1MouseEntered
         btnupload.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_uploadBtnTxt1MouseEntered

    private void uploadBtnTxt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadBtnTxt1MouseExited
        btnupload.setBackground(new Color(122,204,202));
        
    }//GEN-LAST:event_uploadBtnTxt1MouseExited

    private void lblimageInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblimageInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimageInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistrarProducto dialog = new FrmRegistrarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel btndelete;
    private javax.swing.JPanel btnexit;
    private javax.swing.JPanel btninsert;
    private javax.swing.JPanel btnmodify;
    private javax.swing.JPanel btnupload;
    private javax.swing.JComboBox<String> cmbcategoria;
    private javax.swing.JLabel deleteBtnTxt;
    private javax.swing.JLabel exitBtnTxt;
    private javax.swing.JLabel insertBtnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel modifyBtnTxt;
    private javax.swing.JTable tblproducto;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtstock;
    private javax.swing.JLabel uploadBtnTxt1;
    // End of variables declaration//GEN-END:variables
    private DefaultComboBoxModel comboModel;
    private DefaultTableModel tableModel;
}
