/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.beans.Categoria;
import modelo.logic.CategoriaLogic;


public class FrmRegistrarCategoria extends javax.swing.JDialog {
private Categoria categoria;
    /**
     * Creates new form FrmRegistrarCategoria
     */
    public FrmRegistrarCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          this.setLocationRelativeTo(null);
        cargarTablaCate();
        this.setLocationRelativeTo(null);
    }
    
       
    private void cargarTablaCate(){
        tableModel=CategoriaLogic.tableModelCate();
        tblcate.setModel(tableModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcate = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txteliminar = new javax.swing.JTextField();
        btnmodify = new javax.swing.JPanel();
        modifyBtnTxt = new javax.swing.JLabel();
        btnexit = new javax.swing.JPanel();
        exitBtnTxt = new javax.swing.JLabel();
        btninsert = new javax.swing.JPanel();
        insertBtnTxt = new javax.swing.JLabel();
        btndelete = new javax.swing.JPanel();
        deleteBtnTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Categoria");
        setBackground(new java.awt.Color(0, 204, 204));

        PanelGeneral.setBackground(new java.awt.Color(51, 51, 51));
        PanelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "LLENA LOS CAMPOS PEDIDOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Codigo");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        txtcodigo.setBackground(new java.awt.Color(51, 51, 51));
        txtcodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtcodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtnombre.setBackground(new java.awt.Color(51, 51, 51));
        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelGeneral.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 380, 110));
        jPanel1.getAccessibleContext().setAccessibleName("Digita el código y el nombre de la categoría que vas a agregar");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(122, 204, 202));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(51, 51, 51));

        tblcate.setBackground(new java.awt.Color(255, 255, 255));
        tblcate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblcate.setRequestFocusEnabled(false);
        tblcate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcateMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblcate);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        PanelGeneral.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 330, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "LLENA LOS CAMPOS PEDIDOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Codigo");

        txteliminar.setBackground(new java.awt.Color(51, 51, 51));
        txteliminar.setForeground(new java.awt.Color(255, 255, 255));
        txteliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23))
        );

        PanelGeneral.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 380, 80));

        btnmodify.setBackground(new java.awt.Color(122, 204, 202));
        btnmodify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        modifyBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        modifyBtnTxt.setForeground(new java.awt.Color(0, 0, 0));
        modifyBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyBtnTxt.setText("MODIFICAR");
        modifyBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnmodifyLayout = new javax.swing.GroupLayout(btnmodify);
        btnmodify.setLayout(btnmodifyLayout);
        btnmodifyLayout.setHorizontalGroup(
            btnmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modifyBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        btnmodifyLayout.setVerticalGroup(
            btnmodifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modifyBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        PanelGeneral.add(btnmodify, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 130, 40));

        btnexit.setBackground(new java.awt.Color(122, 204, 202));
        btnexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        exitBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        exitBtnTxt.setForeground(new java.awt.Color(0, 0, 0));
        exitBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtnTxt.setText("SALIR");
        exitBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnexitLayout = new javax.swing.GroupLayout(btnexit);
        btnexit.setLayout(btnexitLayout);
        btnexitLayout.setHorizontalGroup(
            btnexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnexitLayout.setVerticalGroup(
            btnexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        PanelGeneral.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, 40));

        btninsert.setBackground(new java.awt.Color(122, 204, 202));
        btninsert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        insertBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        insertBtnTxt.setForeground(new java.awt.Color(0, 0, 0));
        insertBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insertBtnTxt.setText("INSERTAR");
        insertBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btninsertLayout = new javax.swing.GroupLayout(btninsert);
        btninsert.setLayout(btninsertLayout);
        btninsertLayout.setHorizontalGroup(
            btninsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btninsertLayout.setVerticalGroup(
            btninsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        PanelGeneral.add(btninsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 40));

        btndelete.setBackground(new java.awt.Color(122, 204, 202));
        btndelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deleteBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        deleteBtnTxt.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteBtnTxt.setText("ELIMINAR");
        deleteBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btndeleteLayout = new javax.swing.GroupLayout(btndelete);
        btndelete.setLayout(btndeleteLayout);
        btndeleteLayout.setHorizontalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btndeleteLayout.setVerticalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        PanelGeneral.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblcateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcateMouseClicked
        int seleccionar = tblcate.rowAtPoint(evt.getPoint());
        txtcodigo.setText(String.valueOf(tblcate.getValueAt(seleccionar,0)));
        txtnombre.setText(String.valueOf(tblcate.getValueAt(seleccionar,1)));

    }//GEN-LAST:event_tblcateMouseClicked

    private void txteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteliminarActionPerformed

    private void modifyBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyBtnTxtMouseClicked

      try{
            int codigo = Integer.parseInt(txtcodigo.getText());
            String nombre = txtnombre.getText();
                        
            categoria = new Categoria(codigo,nombre);
            
            if(CategoriaLogic.modificarCategoria(categoria)){
                JOptionPane.showMessageDialog(this, "Se modifico correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo modificar");
            }
            this.cargarTablaCate();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        txtcodigo.setText("");
        txtnombre.setText("");
    }//GEN-LAST:event_modifyBtnTxtMouseClicked

    private void modifyBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyBtnTxtMouseEntered
        btnmodify.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_modifyBtnTxtMouseEntered

    private void modifyBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyBtnTxtMouseExited
        btnmodify.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_modifyBtnTxtMouseExited

    private void insertBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnTxtMouseClicked
        // TODO add your handling code here:
         try{
            int codigo = Integer.parseInt(txtcodigo.getText());
            String nombre = txtnombre.getText();

            categoria = new Categoria(codigo, nombre);
            
            if(CategoriaLogic.insertarCategoria(categoria)){
                JOptionPane.showMessageDialog(this, "Se insertó correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo insertar");
            }
            this.cargarTablaCate();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        txtcodigo.setText("");
        txtnombre.setText("");
        
    }//GEN-LAST:event_insertBtnTxtMouseClicked

    private void insertBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnTxtMouseEntered
        // TODO add your handling code here:
        btninsert.setBackground(new Color(133, 226, 235));  
    }//GEN-LAST:event_insertBtnTxtMouseEntered

    private void insertBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnTxtMouseExited
        // TODO add your handling code here:
        btninsert.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_insertBtnTxtMouseExited

    private void exitBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnTxtMouseClicked
        // TODO add your handling code here:
        int valor;
        valor = JOptionPane.showConfirmDialog(this,"¿Seguro que desea salir?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_exitBtnTxtMouseClicked

    private void exitBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnTxtMouseEntered
        // TODO add your handling code here:
        btnexit.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_exitBtnTxtMouseEntered

    private void exitBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnTxtMouseExited
        // TODO add your handling code here:
          btnexit.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_exitBtnTxtMouseExited

    private void deleteBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnTxtMouseClicked
        // TODO add your handling code here:
        try{
            int codigo = Integer.parseInt(txteliminar.getText());
            
            if(CategoriaLogic.eliminarCategoria(codigo)){
                JOptionPane.showMessageDialog(this, "Se elimino correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar");
            }
            this.cargarTablaCate();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        txteliminar.setText("");
        
    }//GEN-LAST:event_deleteBtnTxtMouseClicked

    private void deleteBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnTxtMouseEntered
        // TODO add your handling code here:
        btndelete.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_deleteBtnTxtMouseEntered

    private void deleteBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnTxtMouseExited
        // TODO add your handling code here:
         btndelete.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_deleteBtnTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistrarCategoria dialog = new FrmRegistrarCategoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel btndelete;
    private javax.swing.JPanel btnexit;
    private javax.swing.JPanel btninsert;
    private javax.swing.JPanel btnmodify;
    private javax.swing.JLabel deleteBtnTxt;
    private javax.swing.JLabel exitBtnTxt;
    private javax.swing.JLabel insertBtnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel modifyBtnTxt;
    private javax.swing.JTable tblcate;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txteliminar;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel modelListCat;
      private DefaultTableModel tableModel;
}
