/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.beans.Categoria;
import modelo.beans.Cliente;
import modelo.beans.DetalleVenta;
import modelo.beans.Producto;
import modelo.beans.Venta;
import modelo.logic.ClienteLogic;
import modelo.logic.ProductoLogic;
import modelo.logic.VentaLogic;


/**
 *
 * @author shantal Telecomunica
 */
public class FrmRegistrarVenta extends javax.swing.JDialog {
    private Venta venta;
    
    /**
     * Creates new form FrmRegistrarVenta
     */
    public FrmRegistrarVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        Panelboleta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        txtpreciou = new javax.swing.JTextField();
        txtproducto = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtcategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtpreciot = new javax.swing.JTextField();
        cancelarBtn = new javax.swing.JPanel();
        cancelarBtnTxt = new javax.swing.JLabel();
        salirBtn = new javax.swing.JPanel();
        salirBtnTxt = new javax.swing.JLabel();
        venderBtn = new javax.swing.JPanel();
        venderBtnTxt = new javax.swing.JLabel();
        PanelInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodcliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcodpro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txtcodventa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        LlenarBtn = new javax.swing.JPanel();
        llenarBtnTxt = new javax.swing.JLabel();
        flecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelGeneral.setBackground(new java.awt.Color(51, 51, 51));

        Panelboleta.setBackground(new java.awt.Color(255, 255, 255));
        Panelboleta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "SALIDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NOMBRES:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("APELLIDOS:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("DNI:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("PRECIO UNITARIO:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("PRODUCTO:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CATEGORIA:");

        txtdni.setBackground(new java.awt.Color(51, 51, 51));
        txtdni.setForeground(new java.awt.Color(255, 255, 255));
        txtdni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtpreciou.setBackground(new java.awt.Color(51, 51, 51));
        txtpreciou.setForeground(new java.awt.Color(255, 255, 255));
        txtpreciou.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtproducto.setBackground(new java.awt.Color(51, 51, 51));
        txtproducto.setForeground(new java.awt.Color(255, 255, 255));
        txtproducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtnombre.setBackground(new java.awt.Color(51, 51, 51));
        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtapellido.setBackground(new java.awt.Color(51, 51, 51));
        txtapellido.setForeground(new java.awt.Color(255, 255, 255));
        txtapellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtcategoria.setBackground(new java.awt.Color(51, 51, 51));
        txtcategoria.setForeground(new java.awt.Color(255, 255, 255));
        txtcategoria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("TOTAL A PAGAR:");

        txtpreciot.setBackground(new java.awt.Color(51, 51, 51));
        txtpreciot.setForeground(new java.awt.Color(255, 255, 255));
        txtpreciot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cancelarBtn.setBackground(new java.awt.Color(122, 204, 202));
        cancelarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cancelarBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        cancelarBtnTxt.setForeground(new java.awt.Color(51, 51, 51));
        cancelarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarBtnTxt.setText("CANCELAR");
        cancelarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout cancelarBtnLayout = new javax.swing.GroupLayout(cancelarBtn);
        cancelarBtn.setLayout(cancelarBtnLayout);
        cancelarBtnLayout.setHorizontalGroup(
            cancelarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        cancelarBtnLayout.setVerticalGroup(
            cancelarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        salirBtn.setBackground(new java.awt.Color(122, 204, 202));
        salirBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        salirBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        salirBtnTxt.setForeground(new java.awt.Color(51, 51, 51));
        salirBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirBtnTxt.setText("SALIR");
        salirBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salirBtnLayout = new javax.swing.GroupLayout(salirBtn);
        salirBtn.setLayout(salirBtnLayout);
        salirBtnLayout.setHorizontalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        salirBtnLayout.setVerticalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        venderBtn.setBackground(new java.awt.Color(122, 204, 202));
        venderBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        venderBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        venderBtnTxt.setForeground(new java.awt.Color(51, 51, 51));
        venderBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        venderBtnTxt.setText("VENDER");
        venderBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        venderBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                venderBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                venderBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                venderBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout venderBtnLayout = new javax.swing.GroupLayout(venderBtn);
        venderBtn.setLayout(venderBtnLayout);
        venderBtnLayout.setHorizontalGroup(
            venderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(venderBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        venderBtnLayout.setVerticalGroup(
            venderBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(venderBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelboletaLayout = new javax.swing.GroupLayout(Panelboleta);
        Panelboleta.setLayout(PanelboletaLayout);
        PanelboletaLayout.setHorizontalGroup(
            PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelboletaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelboletaLayout.createSequentialGroup()
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelboletaLayout.createSequentialGroup()
                                .addComponent(venderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelboletaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(34, 34, 34)
                                .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpreciot, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpreciou, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(PanelboletaLayout.createSequentialGroup()
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(13, 13, 13)
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcategoria)
                            .addComponent(txtproducto)
                            .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellido)
                            .addComponent(txtnombre))
                        .addGap(80, 80, 80))))
        );
        PanelboletaLayout.setVerticalGroup(
            PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelboletaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelboletaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelboletaLayout.createSequentialGroup()
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtpreciou, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelboletaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(txtpreciot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelboletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(venderBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        PanelInput.setBackground(new java.awt.Color(255, 255, 255));
        PanelInput.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ENTRADA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CODIGO DE CLIENTE:");

        txtcodcliente.setBackground(new java.awt.Color(51, 51, 51));
        txtcodcliente.setForeground(new java.awt.Color(255, 255, 255));
        txtcodcliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CODIGO DE PRODUCTO:");

        txtcodpro.setBackground(new java.awt.Color(51, 51, 51));
        txtcodpro.setForeground(new java.awt.Color(255, 255, 255));
        txtcodpro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CANTIDAD:");

        txtcantidad.setBackground(new java.awt.Color(51, 51, 51));
        txtcantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtcantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtcodventa.setBackground(new java.awt.Color(51, 51, 51));
        txtcodventa.setForeground(new java.awt.Color(255, 255, 255));
        txtcodventa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CODIGO DE VENTA:");

        LlenarBtn.setBackground(new java.awt.Color(122, 204, 202));
        LlenarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        llenarBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        llenarBtnTxt.setForeground(new java.awt.Color(51, 51, 51));
        llenarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        llenarBtnTxt.setText("GENERAR BOLETA");
        llenarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llenarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llenarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llenarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llenarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LlenarBtnLayout = new javax.swing.GroupLayout(LlenarBtn);
        LlenarBtn.setLayout(LlenarBtnLayout);
        LlenarBtnLayout.setHorizontalGroup(
            LlenarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llenarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        LlenarBtnLayout.setVerticalGroup(
            LlenarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(llenarBtnTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelInputLayout = new javax.swing.GroupLayout(PanelInput);
        PanelInput.setLayout(PanelInputLayout);
        PanelInputLayout.setHorizontalGroup(
            PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputLayout.createSequentialGroup()
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodpro, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(txtcodcliente)
                            .addComponent(txtcantidad)
                            .addComponent(txtcodventa)))
                    .addGroup(PanelInputLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(LlenarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        PanelInputLayout.setVerticalGroup(
            PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcodpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(LlenarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        flecha.setBackground(new java.awt.Color(255, 255, 255));
        flecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/flecha-correcta.png"))); // NOI18N

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGeneralLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(PanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flecha)
                .addGap(18, 18, 18)
                .addComponent(Panelboleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420))
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Panelboleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelGeneralLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(flecha, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(PanelGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llenarBtnTxtMouseClicked

         try{
            int idc = Integer.parseInt(txtcodcliente.getText());int idp = Integer.parseInt(txtcodpro.getText());
            int cant= Integer.parseInt(txtcantidad.getText());
            double total,igv;
            total = (double)(cant*ProductoLogic.obtenerProducto(idp).getPrecio());
            igv = (double)(0.18*cant*ProductoLogic.obtenerProducto(idp).getPrecio());
            txtdni.setText(String.valueOf(ClienteLogic.obtenerCliente(idc).getDni()));
            txtnombre.setText(String.valueOf(ClienteLogic.obtenerCliente(idc).getNombre()));
            txtapellido.setText(String.valueOf(ClienteLogic.obtenerCliente(idc).getApellidos()));
            txtproducto.setText(ProductoLogic.obtenerProducto(idp).getNombre());
            txtcategoria.setText(String.valueOf(ProductoLogic.obtenerProducto(idp).getCategoria()));
            txtpreciou.setText(String.valueOf(ProductoLogic.obtenerProducto(idp).getPrecio()));
            txtpreciot.setText(String.valueOf(total));
         
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_llenarBtnTxtMouseClicked

    private void llenarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llenarBtnTxtMouseEntered
        LlenarBtn.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_llenarBtnTxtMouseEntered

    private void llenarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llenarBtnTxtMouseExited
        LlenarBtn.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_llenarBtnTxtMouseExited

    private void cancelarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBtnTxtMouseClicked
        // TODO add your handling code here:
        txtcodventa.setText(""); txtcodcliente.setText(""); txtcodpro.setText(""); txtcantidad.setText("");
        txtdni.setText("");
        txtnombre.setText("");txtapellido.setText("");txtproducto.setText("");txtcategoria.setText("");
        txtpreciou.setText("");
        txtpreciot.setText("");
    }//GEN-LAST:event_cancelarBtnTxtMouseClicked

    private void cancelarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBtnTxtMouseEntered
cancelarBtn.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_cancelarBtnTxtMouseEntered

    private void cancelarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBtnTxtMouseExited
        cancelarBtn.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_cancelarBtnTxtMouseExited

    private void venderBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venderBtnTxtMouseClicked
        // TODO add your handling code here:
         try {
            int codigoventa = Integer.parseInt(txtcodventa.getText());double total = Double.parseDouble(txtpreciot.getText());
            Date fecha = new Date();
            int idp = Integer.parseInt(txtcodpro.getText());int idc = Integer.parseInt(txtcodcliente.getText());
            int cantidad = Integer.parseInt(txtcantidad.getText());
            double preciou = Double.parseDouble(txtpreciou.getText());
            Producto producto = ProductoLogic.obtenerProducto(idp);
            List<DetalleVenta> ldetalleventa = new ArrayList<>();
            DetalleVenta detalleventa = new DetalleVenta(cantidad, preciou, producto);
            
            ldetalleventa.add(detalleventa);
            Cliente cliente = ClienteLogic.obtenerCliente(idc);
            venta = new Venta(codigoventa, fecha, total, cliente, ldetalleventa);
            

            if(VentaLogic.insertarVenta(venta)){
                JOptionPane.showMessageDialog(this, "Se inserto correctamente");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo insertar");
            }
            
       } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        txtcodventa.setText("");
        txtcodcliente.setText("");
        txtcodpro.setText("");
        txtcantidad.setText("");
        txtdni.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtproducto.setText("");
        txtcategoria.setText("");
        txtpreciou.setText("");
        txtpreciot.setText("");
    }//GEN-LAST:event_venderBtnTxtMouseClicked

    private void venderBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venderBtnTxtMouseEntered
venderBtn.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_venderBtnTxtMouseEntered

    private void venderBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_venderBtnTxtMouseExited
       venderBtn.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_venderBtnTxtMouseExited

    private void salirBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnTxtMouseClicked
        // TODO add your handling code here:
         int valor;
        valor=JOptionPane.showConfirmDialog(this,"¿Seguro que desea salir?","Advertencia",JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_salirBtnTxtMouseClicked

    private void salirBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnTxtMouseEntered
salirBtn.setBackground(new Color(133, 226, 235));
    }//GEN-LAST:event_salirBtnTxtMouseEntered

    private void salirBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnTxtMouseExited
     salirBtn.setBackground(new Color(122,204,202));
    }//GEN-LAST:event_salirBtnTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistrarVenta dialog = new FrmRegistrarVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LlenarBtn;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelInput;
    private javax.swing.JPanel Panelboleta;
    private javax.swing.JPanel cancelarBtn;
    private javax.swing.JLabel cancelarBtnTxt;
    private javax.swing.JLabel flecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel llenarBtnTxt;
    private javax.swing.JPanel salirBtn;
    private javax.swing.JLabel salirBtnTxt;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtcodcliente;
    private javax.swing.JTextField txtcodpro;
    private javax.swing.JTextField txtcodventa;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpreciot;
    private javax.swing.JTextField txtpreciou;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JPanel venderBtn;
    private javax.swing.JLabel venderBtnTxt;
    // End of variables declaration//GEN-END:variables
}
